config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    get 'users/sign_in' => 'devise/sessions#new'
    get 'users/sign_out' => 'devise/sessions#destroy'
    match 'users/:id', to: 'users#show', as: 'user', via: 'get'
  end

  resources :pits do
    put "like", to: "pits#upvote"
      put "dislike", to: "pits#downvote"
    resources :comments do
      put "like", to: "comments#upvote"
      put "dislike", to: "comments#downvote"
    end
  end
  




  root to: 'pages#home'
  get '/about' => 'pages#about'
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_votable
  belongs_to :pit
  belongs_to :user
end

app/models/pit.rb
class Pit < ActiveRecord::Base
  acts_as_votable
  has_many :comments
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  has_many :pits
  has_many :comments
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  def name
    name = first_name + ' ' + last_name
  end


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def after_sign_in_path_for(resource_or_scope)
    root_path
  end

  def youtube_video(url)
    render :partial => 'shared/youtube', :locals => { :url => url }
  end 


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


 def create
  @pit= Pit.find(params[:pit_id])
  @comment = @pit.comments.build(comments_params)
  @comment.user = current_user
  @comment.save

  redirect_to pit_path(@pit)
end

  def destroy
    @pit = Pit.find(params[:pit_id])
    @comment = @pit.comments.find(params[:id])
    @comment.destroy
    redirect_to pit_path(@pit)
end

def upvote
  @pit = Pit.find(params[:pit_id])
  @comment = @pit.comments.find(params[:comment_id])
  @comment.upvote_from current_user
  redirect_to pit_path(@pit)
end

def downvote
  @pit = Pit.find(params[:pit_id])
  @comment = @pit.comments.find(params[:comment_id])
  @comment.downvote_from current_user
  redirect_to pit_path(@pit)
end

def update
end

    


def show  
end

  private

def comments_params
    params.require(:comment).permit(:body, :user_id)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def home
    
end

  def help
  end

  def about
  end

  def contact
  end


end

app/controllers/pits_controller.rb
class PitsController < ApplicationController

def new
  @pit = Pit.new
end

def index
  @pit = Pit.all
  @user = User.find_by(params[:id])
  @pits = Pit.paginate(:page => params[:page]).order('created_at ASC').group_by { |pit| pit.created_at.strftime("%B %Y") }
end




def create
  @user = current_user
  @pit = current_user.pits.create(pit_params)
    if @pit.save
      redirect_to @pit
    else
      render 'new'
    end
end
    


def show
  @pit = Pit.find(params[:id])
end

def edit
end

def update
   @pit = Pit.find(pit_params[:id])
     if @pit.update_attributes(pit_params)
       redirect_to @pit
     end
end

def upvote
  @pit = Pit.find(params[:pit_id])
  @pit.upvote_from current_user
  redirect_to pit_path(@pit)
end

def downvote
  @pit = Pit.find(params[:pit_id])
  @pit.downvote_from current_user
  redirect_to pit_path(@pit)
end


private

def pit_params
    params.require(:pit).permit(:topic, :summary, :image, :video_url, :author, :user_id)
end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
  private
 
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :about)
  end
 
  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  

  def index
    @users = User.all
    authorize User
  end


   def show
    @user = User.find(params[:id])
  end




  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end


#changes

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pits_helper.rb
module PitsHelper

  def convincing_pit
    @pit = Pit.find(params[:id])
    if @pit.get_likes.size.to_i > 5
      @pit.get_likes.size.to_i
    else
      (0)
    end
  end

  
end

app/views/comments/_comment.html.erb
  <div class = "well">
    <p>
    
    <%= comment.body %>
    <p>posted by: <%= comment.user.name %></p>
    <div class = "response">
       <p class = "like-response">Was this response convincing to you?</p>
       <%= link_to "Yes", pit_comment_like_path(@pit, comment), method: :put %>
       <%= link_to "No", pit_comment_dislike_path(@pit, comment), method: :put %>
    </div>

    <div class = "response-convince">
      <p class = "dislike-comment">
        <%= comment.get_dislikes.size %> users found this response unconvincing
      </p>
       <p class = "like-comment">
        <%= comment.get_likes.size %> users found this response convincing</p>
      </p>
    </div>    

  <p>
    <%if comment.user == current_user %>

     <%= link_to 'Destroy Comment', [@pit, comment],
                 method: :delete,
                 data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
    <% end %>             
  </p>
  </div>

app/views/comments/_form.html.erb
<%= form_for([@pit, @pit.comments.build]) do |f| %>
  <p>
    <%= f.label :body %>
    <br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/destroy.js.erb
// $('.delete_comment').bind('ajax:success', function() {  
//         $(this).closest('tr').fadeOut();
// });  

app/views/layouts/_discussion_carousel.html.erb
<div class="container">
  <div class='row'>
    <div class='col-md-offset-2 col-md-8'>
      <div class="carousel slide" data-ride="carousel" id="quote-carousel">
        <!-- Bottom Carousel Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#quote-carousel" data-slide-to="0" class="active"></li>
          <li data-target="#quote-carousel" data-slide-to="1"></li>
          <li data-target="#quote-carousel" data-slide-to="2"></li>
        </ol>
        
        <!-- Carousel Slides / Quotes -->
        <div class="carousel-inner">
        
          <!-- Quote 1 -->
          <div class="item active">
            <blockquote>
              <div class="row">
                <div class="col-sm-3 text-center">
                  <img class="img-circle" src="https://s3.amazonaws.com/uifaces/faces/twitter/kolage/128.jpg" style="width: 100px;height:100px;">
                </div>
                <div class="col-sm-9">
                  <h3><%= link_to 'Recently Created Pits', '#' %></h3>
                  <p>Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit!</p>
                </div>
              </div>
            </blockquote>
          </div>
          <!-- Quote 2 -->
          <div class="item">
            <blockquote>
              <div class="row">
                <div class="col-sm-3 text-center">
                  <img class="img-circle" src="https://s3.amazonaws.com/uifaces/faces/twitter/mijustin/128.jpg" style="width: 100px;height:100px;">
                </div>
                <div class="col-sm-9">
                  <h3><%= link_to 'Recently Created Pits', '#' %></h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam auctor nec lacus ut tempor. Mauris.</p>
                  
                </div>
              </div>
            </blockquote>
          </div>
          <!-- Quote 3 -->
          <div class="item">
            <blockquote>
              <div class="row">
                <div class="col-sm-3 text-center">
                  <img class="img-circle" src="https://s3.amazonaws.com/uifaces/faces/twitter/keizgoesboom/128.jpg" style="width: 100px;height:100px;">
                </div>
                <div class="col-sm-9">
                  <h3><%= link_to 'Recently Created Pits', '#' %></h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut rutrum elit in arcu blandit, eget pretium nisl accumsan. Sed ultricies commodo tortor, eu pretium mauris.</p>
                </div>
              </div>
            </blockquote>
          </div>
        </div>
        
        <!-- Carousel Buttons Next/Prev -->
        <a data-slide="prev" href="#quote-carousel" class="left carousel-control"><i class="fa fa-chevron-left"></i></a>
        <a data-slide="next" href="#quote-carousel" class="right carousel-control"><i class="fa fa-chevron-right"></i></a>
      </div>                          
    </div>
  </div>
</div>

app/views/layouts/_front.html.erb
<html>
    <head>
        <title>Jumbotron Example</title>
        <link rel="stylesheet" href="main.css">
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

        <!-- Optional theme -->
        <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
    </head>

    <body>

     <div class = "container">
       <div class = "jumbotron">
         <center><h1>Welcome to the Firepit!</h1>
         <p>This is the place where sitting by the fire meets the digital world</p>

         <% if current_user && !current_user.sign_in_count.blank? && current_user.sign_in_count == 1 && session[:tour].blank? %>         
         <p>Welcome to the Fire <%=link_to current_user.name, current_user %>!</p>
         <%= link_to "Start New Pit", new_pit_path, class: "btn btn-default" %>
         <%= link_to "Join Existing Pit", pits_path, class: "btn btn-default" %>
         <% elsif user_signed_in? %>
         <!-- If user is logged in then show these 2 buttons and welcome message -->
         <p>Welcome Back! <%=link_to current_user.name, current_user %></p>
         <%= link_to "Start New Pit", new_pit_path, class: "btn btn-default" %>
         <%= link_to "Join Existing Pit", pits_path, class: "btn btn-default" %>
         
             
         <% else %>
         <%= link_to "Join the Pit!", new_user_registration_path, class: "btn btn-default" %>
         <br>
         <br>
         <%= link_to "User Login", user_session_path %>
         </center>
         <% end %>

         
       </div>
     </div>

     <div class = "container">

        <div class = "row">

           <div class = "col-md-6">
             <% unless user_signed_in? %>
             <h3><a href="#">Specific topics with specific people</a></h3>
             <p>Start a topic with a book, video, or just and idea you have. Then invite and discuss</p
             <%= link_to "Start Now", new_pit_path, class: "btn btn-default" %>
             
             <%= link_to "Start Now", new_user_registration_path, class: "btn btn-default" %>
            
           </div> 

         <div class = "col-md-6">
             <h3><a href="#">Share and discuss around our digital fire</a></h3>
             <p>Since the dawn of time, great ideas have manifested themselves and been discussed around the fire. It's no wonder then that creating a digital version of such discussions is a must in our day and age</p>
             <%= link_to "Read More", about_path, class: "btn btn-default" %>
             <% else %>
        <% end %>
           </div> 
        </div>
     </div>

app/views/layouts/_front_header.html.erb
<body>

      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">

          <%= link_to "The Firepit", root_path, id: "logo" %>

          <button class= "navbar-toggle" data-toggle = "collapse" data-target = ".navHeaderCollapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <div class="collapse navbar-collapse navHeaderCollapse">

            <ul class="nav navbar-nav navbar-right">

              <li class="active"><%= link_to "Home", root_path %></li>
              <li><%= link_to "Help", '#' %></li>
              <li><%= link_to "Contact", '#' %></li>
              <li><%= link_to "About", about_path %></li>
              <% if user_signed_in? %>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Logout", destroy_user_session_path,:method => :delete %></li>
              <li><%= link_to "Pits", pits_path %></li>
              <% else %>
              <li><%= link_to "Sign in", user_session_path %></li>
              <% end %>

             <!--  <% if user_signed_in? %>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Home",    root_path %></li>
                <li><%= link_to "Help",    '#' %></li>
                <% else %>
                <li><%= link_to "Sign in", user_session_path %></li>
                <% end %> -->
              


            </ul>
            
          </div>

        </div>


     </div>
     <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</body>

app/views/layouts/_header.html.erb
  

  
    <div class="navbar navbar-inverse navbar-fixed-top">
          
      <div class="container">
            <%= link_to "The Firepit", root_path, id: "logo" %>
  
            <button class= "navbar-toggle" data-toggle = "collapse" data-target = ".navHeaderCollapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
  
            <div class="collapse navbar-collapse navHeaderCollapse">
  
              <ul class="nav navbar-nav navbar-right">
  
                <% if user_signed_in? %>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Home",    root_path %></li>
                <li><%= link_to "Help",    '#' %></li>
                <% else %>
                <li><%= link_to "Sign in", user_session_path %></li>
                <% end %>
                
  
  
              </ul>
              
            </div>
  
          
      
  
       </div>
     </div>

     

app/views/layouts/_home_footer.html.erb
<footer>
<div class="row home-footer">
    <div class="col-md-4">
      <h3>Some Title</h3>
      <p>A little about the above title and summary of whats here</p>
    </div>
    <div class="col-md-4">
      <h3>Another Subtitle</h3>
      <p>Some other shit explaining the shit above and all that good shit</p>
    </div>
    <div class="col-md-4">
      <h3>Another, yet again, subtitle</h3>
      <p>Some more bullshit to make the page render and look pretty</p>
    </div>
  </div>
</footer>

app/views/layouts/_home_header.html.erb
<header id="home-header">
  <div class="container">
    <div class="row"
      <div class="col-lg-12"
      <div class="container">
      <%= link_to "The Firepit", '#', id: "logo" %>
       <p class="login pull-right">
          <% if user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path,:method => :delete, class: "btn btn-default btn-lg" %>
          <% else %>
          <%= link_to "Login", user_session_path, class: "btn btn-default btn-lg" %>
          <% end %>
       </p>
      </div>
      </div>
       
      </div>
    </div>
  <div class="container">
        <div class="row"
        <div class="col-lg-12"
        <div class="header-description">
            <h2>Welcome to the Firepit!</h2>
            <% if user_signed_in? %>
            <%= link_to "Start New Pit", new_pit_path, class: "btn-default-start" %>
            <br>
            <%= link_to "Join Existing Pit", pits_path, class: "btn-default-join" %>
            <% else %>
            <%= link_to "Join the Pit!", new_user_registration_path, class: "header-btn" %>
            <% end %>
          </div>
          <div class="header-features">
            <div class="row">
            <div class="col-lg-6 header-feature">
              <h3><i class="icon-random"></i> &nbsp;Specific topics with specific people</h3>
              <p>Start a topic with a book, video, or just and idea you have. Then invite and discuss</p>
            </div>
            <div class="col-lg-6 header-feature">
              <h3> <i class="icon-group"></i> &nbsp;Share and discuss around our digital fire</h3>
              <p>Since the dawn of time, great ideas have manifested themselves and been discussed around the fire. It's no wonder then that creating a digital version of such discussions is a must in our day and age</p>
            </div>
            </div>
          </div>
      </div>
      </div>
  </div>
  </div>
</header>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>The Firepit</title>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

<body>

      

      <div class="container">
        <%= render 'layouts/front_header' %>
        
      
    
      </div>

    
       
       
   


      <%= yield %>

       <%= debug(params) if Rails.env.development? %>

  </body>
</html>

app/views/pages/about.html.erb
  <% content_for :title do %>About<% end %>

<div class = "container about">

  <div class = "well" >
    <h3>About The Firepit</h3>
    <p>The purpose of this web application is to allow users to create and participate in focused intimate discussions on specific topics created by the user. Users will be rewarded for constructive and logically sound discussions around said topic. Socia media apps like facebook are nice for this in some ways, particularly with the "groups" feature. However, I find that something more geared and specific is needed for some people like myself and others that I know. The aim is really to eliminate uneeded banter and argumentation that goes nowhere. Other web apps certainly allow for good discussion but there is little to stop a good discussion from going bad which is far often the case. I'm hoping that this application can curb some of the issues you commonly see in other like applications around the internet.</p>

    <p> This idea is not my own and was spurned by many real life firepit discussions around a real fire. The participants of those discussions found it was the perfect environment to discuss a great many ideas, both complex and simple at great length, without conflict amongst people who often didn't agree with each other.</p>
  <p>
  This web application was created by Mark Hustad with
  <%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
  from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
  </p>
  </div>
  </div>

app/views/pages/home.html.erb
<%= render 'layouts/front_header' %>
<%= render 'layouts/front' %>

app/views/pits/index.html.erb
<div class = "container list-pits"> 
  <%= link_to "Add New Pit", new_pit_path, class: "btn btn-default" %>
  <br>
  <br>
  <% @pit.each do |pit| %>

 <div class = "row">

   <div class = "container">
    <div class = "well pit-well"> 
       <h3 id="pit-title"><%= link_to pit.topic, pit_path(pit) %></h3>
       <p>by <%= link_to pit.author, '#' %></p>
          <br>
            <p><%= pit.summary %></p>
            <p>Replies (<%= pit.comments.count %>)</p>
          <br>
            <p>Pit Created by: <%= link_to pit.user.name, current_user %> on <%= pit.created_at %></p>
            <%= link_to "Join Pit", '#', class: "btn btn-primary" %>
      </div>
    </div>
      <% end %>
     
  </div>
 </div>

app/views/pits/new.html.erb
<div class="container new-pit">

<%= render 'devise/shared/error_messages', obj: @pit %>

<%= form_for @pit, :html => {:multipart => true} do |f| %>

    <div class = "form-horizontal">

      <div class="form-group">
                   <%= f.label :topic, class: "col-sm-2 control-label" %>
             <div class="col-sm-6">
                   <%= f.text_field :topic, class: "form-control", autofocus: true %>
             </div>  
      </div>

      <div class="form-group">
                   <%= f.label :author, class: "col-sm-2 control-label" %>
             <div class="col-sm-6">
                   <%= f.text_field :author, class: "form-control", :placeholder => "Enter name of book author, lecturer, or presenter" %>
             </div>  
      </div>
      
           <div class="form-group">
                   <%= f.label :summary, class: "col-sm-2 control-label" %>
             <div class="col-sm-6">
                   <%= f.text_area :summary, class: "form-control", :placeholder => "Present an argument for or against the material presented and state why you think it is accurate or not" %>
             </div>  
           </div>
       
           <div class="form-group">
                   <%= f.label :image, class: "col-sm-2 control-label" %>
             <div class="col-sm-6">
                   <%= f.file_field :image, class: "form-control" %>
             </div>  
           </div>
           <div class="form-group">
                   <%= f.label :video, class: "col-sm-2 control-label" %>
             <div class="col-sm-6">
                   <%= f.text_field :video_url, class: "form-control", :placeholder => "example: //www.youtube.com/embed/hBHYdK9xtYs" %>
                   <p class = "youtube-instruction">Must use the shared -> embed option</p>
             </div>  
           </div>
          <div class="form-group">
                <div class="col-sm-offset-2 col-sm-6">
                      <%= f.submit "Start Pit", class: "btn btn-primary" %>
                </div>
          </div>

      


</div>

</div>
</div>



<% end %>

app/views/pits/show.html.erb
<div class="container pit-show">
  <div class="row">
    

   <div class="col-md-8 pit-starter-info">
     <div class="well"> 
     
   <tr>
      <td><%= image_tag avatar_url(@pit.user) %></td>
      <td><strong><%= @pit.user.name %></strong></td>
   </tr>
   <br>
   <br>
      <ul class = "pit-creator-list">
        <li>Pit Ranking</li>
        <li>Email: <%= @pit.user.email %></li>
        <li>Pits Started: <%= @pit.user.pits.count %> </li>
        <li>Convincing arguments made (14)</li>
      </ul>
   


  </div>
     <br>
        </div>
        <div class="col-md-4 pit-info">
          <div class="panel panel-default">
              <div class = "panel-heading">
                <h3>Pit Statistics</h3>
            </div>
            <div class = "panel-body">
              <ul class = "pit-info-list">
                <li>Pit Views</li>
                <li>Pit Ranking</li>
                <li>Pit Category - Book - Philosophy</li>
                
                <li>Convincing arguments made ( <%= convincing_pit %> )</li>
              

                <li>Logical Fallacies (3)</li>
              </ul>
            </div>
          </div>
         </div>

  
  
  <div class="row">
      <div class="col-md-8">
        
<div class="well">
    
    <div class = "pit-image"><%= image_tag @pit.image_url %></div>
    <iframe width="560" height="345" src=<%= @pit.video_url %> frameborder="0" allowfullscreen></iframe>
    <h3 class="pit-title"><%= @pit.topic %></h3>
    <p><%= @pit.summary %></p>
    <p>by <%= @pit.author %></p>
    <br>
    <br>
    <div class = "like-argument">
    <p class = "like-summary">Was this argument convincing to you?</p>
    <%= link_to "Yes", pit_like_path(@pit), method: :put, class: "btn btn-default" %>
    <%= link_to "No", pit_dislike_path(@pit), method: :put, class: "btn btn-default" %>
    </div>
    <div class = "pit-rep">
    <p class = "like-pit"><%= @pit.get_likes.size %> users found this argument convincing</p>
    <p class = "dislike-pit"><%= @pit.get_dislikes.size %> users found this argument unconvincing</p>
    </div>
    <br>
    <br>
    <h3>Responses</h3>
    <%= render @pit.comments %>
    <%= render "comments/form" %>
</li>
   
    </div>
  </div>





 

    
    <div class="col-md-4">
      <div class = "panel panel-default">
        <div class = "panel-heading">
          <h3 class="user-list">Pit Members</h3>
        </div>
        <div class = "panel-body">
      <ul class = "pit-user-list">
        <li>Hustad</li>
        <li>User2</li>
        <li>User3</li>
        <li>User4</li>
        <li>User5</li>
        <li>User6</li>
        <li>User7</li>
        <li>User8</li>
        </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
  
  </div>
</div>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class = "container profile"> 
    <div class = "row-fluid">
        <div class = "col-md-12">
            <div class = "well">
               <h3><%= @user.first_name %> <%= @user.last_name %></h3>
                   <h6><%= image_tag avatar_url(@user) %></h6>
                   <h6>Email: <%= @user.email %></h6>
                   <h6>Pits Started (<%= current_user.pits.count %>)</h6>
                   <br>
                  <div class = "well">
                   <h4>About Me</h4>
                   <p><%= @user.about %></p>
                  </div>
                  <a><%= link_to "Start a new pit", new_pit_path %></a>
                   <br>
                  <a><%= link_to "Join a created pit", pits_path %></a>
                  <br>
                  <a><%= link_to "Edit profile", edit_user_registration_path %></a>
            </div>
        </div>
    </div>
</div>
    

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>